Tensorflow

In [21]:
import tensorflow as tf

In [22]:
matrix = tf.constant(4, shape=(1,1), dtype = tf.float32) # sabit ttensör oluşturur
matrix

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [23]:
matrix = tf.constant([[1,2,3], [4,5,6]], shape=(2,3))
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [24]:
matrix = tf.eye(3) # birim matris
matrix

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [25]:
matrix = tf.ones((4,3))
matrix

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [26]:
matrix = tf.zeros((3,2,7))
matrix

<tf.Tensor: shape=(3, 2, 7), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]], dtype=float32)>

In [27]:
matrix = tf.random.uniform((2, 2), minval=0, maxval=1)
matrix

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.81699765, 0.19791877],
       [0.8034357 , 0.08568561]], dtype=float32)>

In [28]:
matrix = tf.random.normal((3,3), mean=0, stddev=1)
tf.cast(matrix, dtype=tf.float64)

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[ 0.03716828,  0.65263247, -1.30595767],
       [-0.37556374,  0.79439002,  1.22983301],
       [ 1.18519008, -0.2442842 , -0.85158437]])>

In [31]:
matrix = tf.range(10)
matrix = tf.range(start=0,limit=10, delta=0.5)
matrix

<tf.Tensor: shape=(20,), dtype=float32, numpy=
array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5], dtype=float32)>

Matematiksel İşlemler

In [33]:
matrix1 = tf.constant([1,2,3])
matrix2 = tf.constant([9,8,7])

In [40]:
matrix3 = tf.add(matrix1, matrix2)
matrix3

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10])>

In [37]:
matrix1+matrix2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10])>

In [43]:
matrix3 = tf.subtract(matrix1 , matrix2)
matrix3

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4])>

In [44]:
matrix3 = tf.divide(matrix1 , matrix2)
matrix3

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [46]:
matrix3 = tf.multiply(matrix1 , matrix2)
matrix3

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21])>